### ISSUE TITLE
Installer Error Line 239

### ISSUE THREAD

**Issue by benichmt1** [danslimmon/oscar#22]
Hi,
When I try to run the installer script, it gets choked at a certain point, no matter whether I pick email or Twilio for notifications.

Here's the output I get:

Traceback (most recent call last):
  File "./install.py", line 239, in <module>
    '''.format(**locals()))
KeyError: 'twilio_src'

I get something similar to this when I choose text. I'm currently trying to get it figured out by just creating the conf file manually, but I thought it might be helpful to report.

**Comment by CloCkWeRX** [comment]
d148b339bc98e533c81a6b5a61d19d562665a992 #35 #29
