### ISSUE TITLE
Local IP sent in text: cant Teach Oscar.

### ISSUE THREAD

**Issue by olujoe** [danslimmon/oscar#30]
Can we edit the learning on Trello instead

I have a variable ip router at home so when I shut it down and restart it I always get a new ip, further more the pi is on a floating 192.168...... ip so when I get a text its no use and I cant help oscar learn, this is what I get in my text.

Hi! Oscar here. You scanned a code I didn't recognize. Care to fill me in?  http://192.168.1.5/learn-barcode/qsigTIKY7rRS

**Comment by CloCkWeRX** [comment]
The js-yaml problem is fixed in master, and the variable IP issue is as per the .local address solution

**Comment by Kimsipi** [comment]
I have the same issue and I have done all the above , what are we using as webserver?
