### ISSUE TITLE
getting "install.py" in the right spot on the raspberry

### ISSUE THREAD

**Issue by shadynastyphd** [danslimmon/oscar#36]
i am in no way, shape, or form a linux user so i am crazy noob status here, but id like to set up oscar for my girlfriend. i have not been able to install the "install.py". my question is where exactly does it have to be on the system for the easy install to recognize it? when i type "sudo easy_install install.py" it ends up saying "no local or download links found for install.py" i have went to the website on the raspberry pi and downloaded directly and also carried over from a flash drive. halp! please. and thanks in advance...

**Comment by CloCkWeRX** [comment]
You need to ensure you are running easy install from a git checkout as a starting point...
