### ISSUE TITLE
fatal error: yaml.h

### ISSUE THREAD

**Issue by derekdickerson** [danslimmon/oscar#39]
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-armv6l-2.7/check_libyaml.c -o build/temp.linux-armv6l-2.7/check_libyaml.o
    build/temp.linux-armv6l-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory

**Comment by CloCkWeRX** [comment]
Got any reproduce steps for this one?

**Comment by CloCkWeRX** [comment]
https://github.com/jasperproject/jasper-client/issues/268 sounds similar, I recommend following their advice around the easy_install method
