### ISSUE TITLE
Install script fails KeyError: 'gmail_user'

### ISSUE THREAD

**Issue by derekdickerson** [danslimmon/oscar#40]
dot@1.0.2 node_modules/dot

node-trello@0.1.5 node_modules/node-trello
├── oauth@0.9.7
├── coffee-script@1.3.2
└── request@2.12.0

jade@1.7.0 node_modules/jade
├── character-parser@1.2.0
├── commander@2.1.0
├── void-elements@1.0.0
├── mkdirp@0.5.0 (minimist@0.0.8)
├── monocle@1.1.51 (readdirp@0.2.5)
├── transformers@2.1.0 (promise@2.0.0, css@1.0.8, uglify-js@2.2.5)
├── constantinople@2.0.1 (uglify-js@2.4.15)
└── with@3.0.1 (uglify-js@2.4.15)

express@3.4.4 node_modules/express
├── methods@0.1.0
├── cookie-signature@1.0.1
├── range-parser@0.0.4
├── fresh@0.2.0
├── buffer-crc32@0.2.1
├── cookie@0.1.0
├── mkdirp@0.3.5
├── debug@2.0.0 (ms@0.6.2)
├── commander@1.3.2 (keypress@0.1.0)
├── send@0.1.4 (mime@1.2.11)
└── connect@2.11.0 (methods@0.0.1, uid2@0.0.3, pause@0.0.1, raw-body@0.0.3, qs@0.6.5, bytes@0.2.1, negotiator@0.3.0, multiparty@2.2.0)
Traceback (most recent call last):
  File "./install.py", line 239, in <module>
    '''.format(**locals()))
KeyError: 'gmail_user'

**Comment by CloCkWeRX** [comment]
d148b339bc98e533c81a6b5a61d19d562665a992 and #29 should have resolved this
