### ISSUE TITLE
Install Error: KeyError: 'twilio_scr'

### ISSUE THREAD

**Issue by Spokehedz** [danslimmon/oscar#41]
Fresh install of Raspbian, cloned oscar from github, and then ran $sudo ./install.py and after a long, long time, spits out this error:

Traceback (most recent call last):
  File "./install.py", line 239, in <module>
    '''.format(**locals()))
KeyError: 'twilio_src'

Didn't even pick twilio. Picked Gmail.

**Comment by CloCkWeRX** [comment]
#29
