### ISSUE TITLE
scan.py line 143 and 222 error UnicodeDecodeError: 'ascii' codec can't decode byte 0xa0 in position 210: ordinal not in range(128)

### ISSUE THREAD

**Issue by terxw** [danslimmon/oscar#44]
i am scanning slovak butter, it is recognized form online dataase, but description contains UTF-8 charakter "č", which is causing termination of scan.py process, 
After some probing I came to conclusion that problem is with  variable desc from line 143 and later usage of this variable
i tried to add .encode('UTF-8') to strings used in connection with desc variable, to no avail.
Can someone look into it, or help me how to properly handle special characters?

**Comment by terxw** [comment]
adding after line 202
'''
desc = u.get_description(barcode)
'''

'''
desc = u.get_description(barcode)
a = unidecode(desc)
        desc = a
'''
and of course

'''
from unidecode import unidecode
'''
i have not a problem fith this error

Suggestion: when item is not in recognized in product description rules
Don't know what to add for product description ''
send email to create new rule in oscar_db

**Comment by CloCkWeRX** [comment]
Can you add a pull request for this?

**Comment by skrobul** [comment]
@terxw your suggestion is solved by #47  and original problem possibly in #49. I was trying hard to remember any slovak butter names, but the only one I came up with was Tradične Maslo which has barcode of 8588000695041 but DigitEyes returns it without special characters. Any chance you could find the original product code?
