### ISSUE TITLE
KeyError:'barcode'

### ISSUE THREAD

**Issue by jongalbreath** [danslimmon/oscar#50]
Hello,
I've been playing with Oscar on and off for a few months while I get to know Raspberry Pi and Python.  I had it running for a little while back in September, then tried to tweak something and broke it.  Now I've wiped everything and started over, but I'm having some problems.

I'm using the Raspbian Wheezy image as I couldn't get install.py to complete on Jessie.

I've copied all Oscar code from Git to /var/oscar and run install.py as
  sudo python install.py

The install completes and last night I had a couple successful scans, but for some reason, now I'm only getting the following errors in oscar_scan.log:

Waiting for scanner data
Scanned barcode '073852096743'
Traceback (most recent call last):
  File "/var/oscar/scan.py", line 224, in <module>
    barcode_rule = match_barcode_rule(trello_db, barcode)
  File "/var/oscar/scan.py", line 161, in match_barcode_rule
    if r['barcode'] == barcode:
KeyError: 'barcode'

This should pull up a bottle of Purell.

I haven't changed anything from last night when I scanned a bottle of water and it successfully added a learning opportunity.

I'm new to Python and Git, so it's totally possible I've flubbed the install somehow.  Any assistance/tips would be greatly appreciated.

Is there a recommended installation location?  I'm used to Windows/Mac where install locations are mostly irrelevant.

**Comment by bergkoet** [comment]
It sounds like one of the barcode rules is corrupted.  Check the barcode_rules list on the oscar_db board in Trello.  Each of the cards there should look like:
{"barcode":"052427780508","item":"glue"}
If one of them is missing the "barcode" part (or even if the word is misspelled), it would cause that error.

**Comment by jongalbreath** [comment]
Success!  Thank you!  :smile:
