### ISSUE TITLE
Install hanging? (or should I wait longer than 6 hours?)

### ISSUE THREAD

**Issue by Jonovich** [danslimmon/oscar#51]
Hi folks,

I'm installing this on a Raspberry Pi Zero that's running Jessie (with all updates applied) - the install process goes through all the pre-amble, collecting the various config / credentials, but then seems to get stuck at the following point, which is about fifteen minutes in: -

  g++ '-DENABLE_DEBUGGER_SUPPORT' '-DENABLE_EXTRA_CHECKS' '-DV8_TARGET_ARCH_ARM' '-DUSE_EABI_HARDFLOAT=1' '-DCAN_USE_VFP2_INSTRUCTIONS' -I../deps/v8/src  -Wall -Wextra -Wno-unused-parameter -pthread -fno-strict-aliasing -mfloat-abi=hard -O2 -fno-strict-aliasing -fno-tree-vrp -fno-rtti -fno-exceptions -MMD -MF /home/pi/oscar-master/node-v0.10.22/out/Release/.deps//home/pi/oscar-master/node-v0.10.22/out/Release/obj.target/v8_base/deps/v8/src/builtins.o.d.raw  -c -o /home/pi/oscar-master/node-v0.10.22/out/Release/obj.target/v8_base/deps/v8/src/builtins.o ../deps/v8/src/builtins.cc

Process doesn't seem to get any further, it's been at this point for over six hours - CPU is ticking over at 2 to 5%. No errors, but no further activity. Any idea's where there maybe a log or audit file that can tell me what's going wrong?

Any help greatly appreciated,

Jon

**Comment by jongalbreath** [comment]
I had this issue as well on a Raspberry Pi 2 with Jessie.  If you can run Wheezy on the Zero, try that.

**Comment by Jonovich** [comment]
Thanks Jongalbreath, although it seems wheezy on a PiZero isn't as straightforward as I thought :(

**Comment by Jonovich** [comment]
Quick update - All sorted - found a hack to get Wheezy on the zero and the install completed without problem! Slight technical issue with the SMS messages not coming through for queries, but I'll get to the bottom of that.
Thanks muchly,
Jon
